# Generated by Django 5.1.6 on 2025-02-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('extra_passengers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('trip_date', models.DateField()),
                ('trip_cost', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Processing', 'Processing'), ('Awaiting Invoice', 'Awaiting Invoice')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='carHires.location')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='carHires.location')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carHires.vendor')),
            ],
        ),
    ]
