# Generated by Django 5.1.6 on 2025-02-10 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_per_night', models.PositiveIntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelBookings.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Booking',
                'verbose_name_plural': 'Hotel Bookings',
                'ordering': ['-check_in'],
            },
        ),
    ]
