# Generated by Django 5.1.6 on 2025-02-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='paid',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
